# Generated by Django 6.0.6 on 2026-06-10 10:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_catagory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
